default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: world_book_development

test:
  <<: *default
  database: world_book_test
production:
  <<: *default
  database: world_book_production
  username: world_book
  password: <%= ENV['WORLD_BOOK_DATABASE_PASSWORD'] %>
